### ISSUE TITLE
css liquid tag not working

### ISSUE THREAD

**Issue by maty974** [maty974/maty974.github.io#5]
I was unable to make it work, use Liquid tag in .css file to simply change color of the page title
 [previous css liquid test](https://github.com/maty974/maty974.github.io/commit/a0a73f75e606471823a06285c12f9307d967b84e#diff-fb1c07274e655c422fdabaf32d28b4d0L139)

is it a bug ? is it me ? 

Any idea @fabic ?

**Comment by fabic** [comment]
Dunno: it should have worked -\_-
